# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.1.1
_src_path: gh:radio-aktywne/template-app-next
accountname: radio-aktywne
appname: weblounge
description: Emission prerecordings web UI 📼
docs: true
docsurl: https://radio-aktywne.github.io/app-weblounge
envprefix: WEBLOUNGE
imagename: apps/weblounge
keyprefix: weblounge
port: 39000
registry: true
releases: true
reponame: app-weblounge
repourl: https://github.com/radio-aktywne/app-weblounge
