services:
  weblounge:
    build:
      context: ./
      network: host
    environment:
      - "WEBLOUNGE__SERVER__HOST=${WEBLOUNGE__SERVER__HOST:-0.0.0.0}"
      - "WEBLOUNGE__SERVER__PORT=${WEBLOUNGE__SERVER__PORT:-39000}"
      - "WEBLOUNGE__EMILOUNGE__HTTP__SCHEME=${WEBLOUNGE__EMILOUNGE__HTTP__SCHEME:-http}"
      - "WEBLOUNGE__EMILOUNGE__HTTP__HOST=${WEBLOUNGE__EMILOUNGE__HTTP__HOST:-localhost}"
      - "WEBLOUNGE__EMILOUNGE__HTTP__PORT=${WEBLOUNGE__EMILOUNGE__HTTP__PORT:-28000}"
      - "WEBLOUNGE__EMILOUNGE__HTTP__PATH=${WEBLOUNGE__EMILOUNGE__HTTP__PATH:-}"
      - "WEBLOUNGE__EMISHOWS__HTTP__SCHEME=${WEBLOUNGE__EMISHOWS__HTTP__SCHEME:-http}"
      - "WEBLOUNGE__EMISHOWS__HTTP__HOST=${WEBLOUNGE__EMISHOWS__HTTP__HOST:-localhost}"
      - "WEBLOUNGE__EMISHOWS__HTTP__PORT=${WEBLOUNGE__EMISHOWS__HTTP__PORT:-35000}"
      - "WEBLOUNGE__EMISHOWS__HTTP__PATH=${WEBLOUNGE__EMISHOWS__HTTP__PATH:-}"
    network_mode: host
